AWSTemplateFormatVersion: 2010-09-09
Description: "EC2 Servers"

Parameters:
  ImageId:
    Type: AWS::EC2::Image::Id
  InstanceType:
    Type: String
    Default: "t2.micro"
    
#Mappings: 

Resources:
  MyEC2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      BlockDeviceMappings: 
      - DeviceName: "/dev/xvda"
        Ebs: 
          VolumeType: "io1"
          Iops: "200"
          DeleteOnTermination: "True"
          VolumeSize: "8"

