AWSTemplateFormatVersion: 2010-09-09
Description: "Ec2 web server"

Parameters:
  SubnetId:
    Type: AWS::EC2::Subnet::Id
  ImageId:
    Type: AWS::EC2::Image::Id
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName


Resources: 
  EC2SGInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: "t2.micro"
      KeyName: !Ref KeyName
      SubnetId: !Ref SubnetId
      SecurityGroupIds: 
        - !ImportValue SecurityGroupId