AWSTemplateFormatVersion: 2010-09-09
Description: "Ec2 web server"

Parameters:
  ImageId:
    Type: AWS::EC2::Image::Id
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
  InstanceType:
    Type: String
  SecurityGroup:
    Type: List<AWS::EC2::SecurityGroup::Id>


Resources: 
  EC2SGInstance:
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      SecurityGroupIds: !Ref SecurityGroup