AWSTemplateFormatVersion: 2010-09-09
Description: "Security Group"

Parameters:
  myVPC: 
    Type: AWS::EC2::VPC::Id

Resources: 
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to client host
      VpcId: !Ref myVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0

Outputs:
  SGExport:
    Description: "Value of Security group id"
    Value: !Ref SecurityGroup
    Export:
      Name: SecurityGroupId